[features]
seeds = false
skip-lint = false
[programs.localnet]
liberte_program = "4bXLmkHeyEuJYWLanTNCjd9xgkzK1sy2ud4TkUAXFEbk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/spacemandev/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
